# Generated by Django 5.0.6 on 2024-12-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='scores',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alternative')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.criterion')),
            ],
        ),
    ]
