# Generated by Django 5.0.6 on 2024-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_alternative_scores_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
