# Generated by Django 5.0.6 on 2024-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_criterion_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='preference_type',
            field=models.CharField(choices=[('max', 'Лучше наибольший'), ('min', 'Лучше наименьший')], default='max', max_length=10),
        ),
    ]
