# Generated by Django 5.0.6 on 2024-12-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_criterion_preference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.expert'),
            preserve_default=False,
        ),
    ]
