# Generated by Django 5.0.6 on 2024-12-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expert_score_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
